
<!DOCTYPE html>
<html lang="fr">    
    <head>
        <!-- encodage de la page -->
        <meta charset="utf-8"/>
        <!-- petite déscription du site pour les robots google .... -->
        <meta name="description" content="description de la page"/>
        <!-- balise meta keywords permettant un bon référencement naturel supplémentaire -->
        <meta name="keywords" content="mots-clé1, mots-clé2, ..."/>

        <!-- attribution d'un titre à la page internet -->
        <title>Alice Vision</title>
        <!-- appel de la feuille de style pour la page index.php-->
        <link rel="stylesheet" href="Design/css/global.css"/>

       <!-- <link rel="stylesheet" href="Design/css/jquery.ui.css"/>
        <link rel="stylesheet" href="Design/css/jquery.ui.html4.css"/>-->
        <link rel="shortcut icon" type="image/x-icon" href="" />
       <!-- <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Monsieur+La+Doulaise|Rouge+Script|Tangerine"/>-->
        <script type="text/javascript" src="Design/js/jquery-1.11.1.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i" rel="stylesheet"> 
    </head>
    <body>
        <div id="borderTop"></div>
        <div id="header">
            <img id="logoTop" src="Design/img/logoNoir.png"/>
            <div id="menu">
                <ul>
                    <li><a href="index.php">Home</a></li>
                    <li><a href="Template/page1.php">Photogrammetry</a></li>
                    <li><a href="Template/projet.php">Project</a></li>
                    <li><a href="">About Us</a></li>
                    <li><a href="https://openmvg.readthedocs.io/en/latest/">Docs</a></li>

                </ul>
            </div>
            <div class="clear"></div>
            
        </div>
        <div id="content">
            <div id="aliceVisionFirstPromo">
                <div id="scene"></div> 
                <div id="avTextPromo">
                    <h1>Welcome to AliceVision </h1>
                    <h2>The goal of any computer vision software that captures the geometry of a scene can be described as “given a set of input photographs ”.
                     </h2>
                </div>
            </div>
            <div class="clear"></div>
            <div id="objectif">
                <div>
                    <h1>Objective</h1>
                    <p>The goal of dense modeling of the scene is the result yielded by chaining two computer vision-based pipelines, namely the “Structure-from-Motion” (SfM) and the “Multi View Stereo” (MVS) modules.</p>
                </div>
                <div>
                    <iframe  src="https://www.youtube.com/embed/1-v1e3fsnj0" frameborder="0" allowfullscreen></iframe>
                </div>
            <div class="clear"></div>
            </div>
            <div id="libsDiv">
               <!-- <svg  xmlns="http://www.w3.org/2000/svg " viewBox="0 0 1000 300">
                   
                    <polygon points="0 0,  400 0, 200 300, 0 300"><text>La librairie</text></polygon>
                    <polygon points="400 0,  600 0, 400 300, 200 300"><image x="0" y="0" xlink:href="Design/img/pattern2F.jpg"></image></polygon>
                    <polygon points="600 0, 800 0, 600 300, 400 300"/>
                    <polygon points="800 0, 1000 0, 800 300, 600 300"/>
                    <polygon points="1000 0, 1000 300, 800 300"/>

                </svg>-->
                <h1>The Library</h1>

                <div id="libContent">
                    <div>
                        <div class="parallelogramme"></div>
                        <h3>Structure from Motion</h3>
                        <h4>Photomodeling plugin - Autodesk © Maya</h4>
                        <p>MayaMVG allows graphic artists to do photomodeling on top of a 3D reconstruction (point cloud and cameras) with pixel precision.</p>
                    </div>
                    <div>
                        <div class="parallelogramme"></div>
                        <h3>MultiView Stereo</h3>
                        <h4>Concentric Circles Tag</h4>
                        <p>This library allows you to detect and identify CCTag markers. Such marker system can deliver sub-pixel precision while being largely robust to challenging shooting conditions (e.g. motion blur, occlusion and poor lighting conditions). </p>
                    </div>
                    <div>
                        <div class="parallelogramme"></div>
                        <h3>Camera Tracking</h3>
                        <h4>OpenFX Camera Localization and Calibration plugins.</h4>
                        <p>The CameraLocalizer plugin estimates the camera pose of an image regarding an existing 3D reconstruction generated by openMVG. The plugin supports multiple clips in input to localize a RIG of cameras. </p>
                    </div>

                </div>
                 <div class="clear"></div>

                
            </div>
            <div id = "mikrosDiv">
                <div>
                    <h1>Alice Vision on Mikros</h1>
                    <p>Alice Vision est utilisée par la société Mikros. Elle l'utilise pour la réalisation d'effet speciaux et de film fantastique.</p>

                </div>
                <div>
                    <iframe  src="https://www.youtube.com/embed/2Lh0dSRqH4E" frameborder="0" allowfullscreen></iframe>
                </div>
                 <div class="clear"></div>
            </div>
           
            <div id="softDiv">
                <h1>Softwares</h1>

                <div id="softContent">
                    <div>
                        <div class="parallelogramme"></div>
                        <h3>Maya MVG</h3>
                        <h4>Photomodeling plugin - Autodesk © Maya</h4>
                        <p>MayaMVG allows graphic artists to do photomodeling on top of a 3D reconstruction (point cloud and cameras) with pixel precision.</p>
                    </div>
                    <div>
                        <div class="parallelogramme"></div>
                        <h3>Meshroom</h3>
                        <h4>Concentric Circles Tag</h4>
                        <p>This library allows you to detect and identify CCTag markers. Such marker system can deliver sub-pixel precision while being largely robust to challenging shooting conditions (e.g. motion blur, occlusion and poor lighting conditions). </p>
                    </div>
                    <div>
                        <div class="parallelogramme"></div>
                        <h3>OFX MVG</h3>
                        <h4>OpenFX Camera Localization and Calibration plugins.</h4>
                        <p>The CameraLocalizer plugin estimates the camera pose of an image regarding an existing 3D reconstruction generated by openMVG. The plugin supports multiple clips in input to localize a RIG of cameras. </p>
                    </div>
                </div>

            </div>
            <div id="promoAlgo">
                <h1>Découvrez le fonctionnement d'Alice Vision étape par étape.</h1>
                <div id="steps">


                    <div id="c1a"></div>
                    <div id="c1b"><p><a href="">1</a></p></div>
                    <div id="line1"></div>

                    <div id="c2a"></div>
                    <div id="c2b"><p><a href="">2</a></p></div>
                    <div id="line2"></div>

                     <div id="c3a"></div>
                    <div id="c3b"><p><a href="">3</a></p></div>
                    <div id="line3"></div>

                     <div id="c4a"></div>
                    <div id="c4b"><p><a href="">4</a></p></div>
                    <div id="line4"></div>

                     <div id="c5a"></div>
                    <div id="c5b"><p><a href="">5</a></p></div>
                    <div id="line5"></div>

                     <div id="c6a"></div>
                    <div id="c6b"><p><a href="">6</a></p></div>
                    <div id="line6"></div>

                     <div id="c7a"></div>
                    <div id="c7b"><p><a href="">7</a></p></div>
                    <div id="line7"></div>

                     <div id="c8a"></div>
                    <div id="c8b"><p><a href="">8</a></p></div>
                </div>
                <div class="clear"></div>
            </div>
            <div id="openSource">
                <h1>Open Source</h1>
                <p>We build a fully integrated software for 3D reconstruction, photomodeling and camera tracking. We aim to provide a strong software basis with state-of-the-art computer vision algorithms that can be tested, analyzed and reused. Links between academia and industry is a requirement to provide cutting-edge algorithms with the robustness and the quality required all along the visual effects and shooting process.
                The POPART software builds on a set of core libraries, both newly written ones and such that are adapted from existing software. All of these core libraries are based upon open standards and released in open source. This open approach enables both us and other users to achieve a high degree of integration and easy customisation for any studio pipeline.
                </p>
                <p>Beyond our project objectives, open source is a way of life. We love to exchange ideas, improve ourselves while making improvements for other people and discover new collaboration opportunities to expand everybody’s horizon.</p>
            </div>
            

        </div>
        <div id="footer">
            <!--<div>
                <img src="Design/img/logoNoir.png"/>
                <p><!--Alice vision build a fully integrated software for 3D reconstruction, photomodeling and camera tracking. We aim to provide a strong software basis with state-of-the-art computer vision algorithms that can be tested, analyzed and reused.<p>
            </div>-->
            <div id="informations">
                <div>
                    <h2>Informations</h2>
                    <a href="">Contact Us</a>  
                    <a href="">About Us</a>
                    <a href="">History</a>
                </div>
                <div>
                    <h2>Alice Vision</h2>
                    <a href=""> Documentation</a>
                    <a href="">Step by Step</a>              
                </div>

                <div>
                    <h2>The Softwares</h2>
                    <a href=""> Maya MVG</a>
                    <a href="">Meshroom</a>   
                    <a href="">OFX MVG</a>   
                </div>
                <div id="partenaire">
                    <h2>Partenaires</h2>
                    <img src="Design/img/partenaire1.png"/>
                    <img src="Design/img/partenaire2.png"/>
                    <img src="Design/img/partenaire3.png"/>
                    <img src="Design/img/partenaire4.png"/>
                </div>
                
            </div>
            <div class="clear"></div>



        </div>
        <div id="copyRight"><p> Copyright © 2017 - Alice Vision - All rights reserved</p></div>
        <div id="borderBottom"></div>


        <script src="Design/js/mainJs.js"></script>
        <script src="Design/js/utilisationjson.js"></script>
        <script src="js/three.js"></script>

        <script src="js/DDSLoader.js"></script>
        <script src="js/MTLLoader.js"></script>
        <script src="js/OBJLoader.js"></script>

        <script src="js/Detector.js"></script>
        <script src="js/OrbitControls.js"></script>     

        <script src="js/stats.min.js"></script>

        <script src="js/3d.js"></script>
        
        <script type="text/javascript" src="Design/js/jquery-ui-1.8.20.custom.min.js"></script>
       <!-- <script type="text/javascript" src="Design/js/modernizr.2.5.3.min.js"></script>-->
    </body>
</html>